sudo: false
language: python
python:
- 2.6
- 2.7
- 3.3
- 3.4
- 3.5
before_install:
- npm install bats
install:
- pip install -e .
- pip install "file://`pwd`#egg=mkwheelhouse[tests]"
before_script:
- test/fixtures.py create
script:
- '[[ "$TRAVIS_PYTHON_VERSION" = "2.6" ]] || pre-commit run --all-files'
- bats test/test.bats
after_script:
- test/fixtures.py delete
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: benesch
  on:
    tags: true
  password:
    secure: NIy//LpwQrQ6tGA/+jZCjgewqj4/TwMkjM8IDP7aKKQgDImqGFhzA0otdd5vitJFui2yDetrVubukCVpoTsGZBf0vi+Oy1O77jhJV9noWQKgTjWQiDhJSdPsbbGBfiXBzLW/9ZiTTHKbQiIy6VlPjqSSYEqsj4hk0zSACojwJWM=
env:
  global:
  - MKWHEELHOUSE_BUCKET_STANDARD="travis-$TRAVIS_JOB_NUMBER.mkwheelhouse.com"
  - MKWHEELHOUSE_BUCKET_NONSTANDARD="travis-$TRAVIS_JOB_NUMBER.eu.mkwheelhouse.com"
  - secure: IVLpsOkFZer8m5oO3vZDhyg/lChlO/ZdZbw2LsQkPpxjpx8nzkksJzS33N+Vyk7RD/7RkRNMag2qRAIbauqV2xyMu+mCSHp/MznBnpGBc5DO62Cc4AZrPpzTL5JCBjzxpombaoTfhLRr15wQ7jMAMBBpxsxfNWlKPO9i1icRL5g=
  - secure: hoS+2oDLCByaeQQ21fM3z+h8Y0Da0tx2+FloEr483Xdv01N8ChzEoRWlvl7e9WF/bI7zMWPRmrpVOKxV095Y0+wlzDXRlGOA+2qr2F5KsiYvH/2yNtO3pFMs4FjKYg0dFXZpvXNhDPion98ish6zFsSAdy2h/HnV8b2hr/8D0Tk=
